### ISSUE TITLE
Water Tower 2 is rotated 90 degrees CCW from the prefab's rotation.

### ISSUE THREAD

**Issue by WhistleWiz** [Insprill/dv-mapify#27]
The prefab snaps to points and all that, but then is rotated when viewed ingame. Cannot use the turning wheel to rotate it on top of a locomotive either. All other prefabs do not have this rotation.
![image](https://github.com/Insprill/dv-mapify/assets/9304724/5b096769-0dbf-4e74-a655-f221d9967c8c)

**Comment by Insprill** [comment]
The same issue is present with the dumpster prefab.
