### ISSUE TITLE
Shop doesn't spawn, just a cash register

### ISSUE THREAD

**Issue by t0stiman** [Insprill/dv-mapify#38]
![image](https://github.com/Insprill/dv-mapify/assets/18124323/f5a2ab62-fbc7-4a87-a333-f238bfe63bad)

![afbeelding](https://github.com/Insprill/dv-mapify/assets/18124323/c0eafa93-f2c0-4400-8ed2-fcdccdeeab78)

This bug is probably caused by one of my recent commits because @WhistleWiz doesn't have this problem.

**Comment by Insprill** [comment]
You can use the `git bisect` command to figure out which commit caused it. You mark which commit is good, which is bad, and it'll keep checking out commits in between until it finds the problematic one.
