### ISSUE TITLE
Stations have missing translation

### ISSUE THREAD

**Issue by Insprill** [Insprill/dv-mapify#39]

**Comment by t0stiman** [comment]
On job booklets:

![afbeelding](https://github.com/Insprill/dv-mapify/assets/18124323/c86fbe59-7fb8-4063-b8aa-b025962c763a)

When teleporting to a station:

![afbeelding](https://github.com/Insprill/dv-mapify/assets/18124323/6a481327-2359-406a-82b6-031eece8c2f6)

I have the game set to English.

**Comment by t0stiman** [comment]
I'm working on fixing the job booklets.
