### ISSUE TITLE
Missing scanner in the stores

### ISSUE THREAD

**Issue by t0stiman** [Insprill/dv-mapify#46]
Can't buy items because there is no scanner:

![afbeelding](https://github.com/Insprill/dv-mapify/assets/18124323/0fad06a4-c553-44e4-a3b2-741dc95077b9)

Maybe the scanner falls through the ground like in #28

**Comment by t0stiman** [comment]
The scanner is right where it's supposed to be, it's just not active:

![afbeelding](https://github.com/Insprill/dv-mapify/assets/18124323/b9be2cb7-8461-4fc3-8470-4c5dc267c364)

Activating the object with Unity Runtime Editor makes it show up:

![afbeelding](https://github.com/Insprill/dv-mapify/assets/18124323/7c371dcf-a22c-4fb4-8086-28615c97be63)

I don't know how to properly solve this. @Insprill any ideas?

**Comment by Insprill** [comment]
Probably something with the `PlayerDistanceMultipleGameObjectsOptimizer` or `PlayerDistanceGameObjectsDisabler`, whichever one it uses. Most likely it isn't getting added.

**Comment by t0stiman** [comment]
this issue has disappeared.
