### ISSUE TITLE
Another problem

### ISSUE THREAD

**Issue by Kelticcol** [Insprill/dv-mapify#55]
Another problem i encountered :
![20231216221134_1](https://github.com/Insprill/dv-mapify/assets/152837201/0a3e514d-bbc9-444a-b048-9978c6142932)

This is a new one, any clues how to fix?

Cheers

**Comment by t0stiman** [comment]
Please send your Player.log file, it has more information.  
`%AppData%/../LocalLow/Altfuture/Derail Valley/player.log`

**Comment by Kelticcol** [comment]
Here you go.

Cheers.

**Comment by t0stiman** [comment]
There is no file attached to your message.  
If you attached it to the email, i guess that doesn't work

**Comment by Kelticcol** [comment]
Try these. cheers by the way

[Player.log](https://github.com/Insprill/dv-mapify/files/13696059/Player.log)
[Player-prev.log](https://github.com/Insprill/dv-mapify/files/13696060/Player-prev.log)

**Comment by Kelticcol** [comment]
So i made another map, completely basic one, dead flat, no trees, no other buildings, just the following; 
1 straight track
2 stations
1 shop
2 buffer points
1 basic service point (the one for diesel locomotives)

And it don't load either, i think its a serious bug somewhere in the mapify core or DV.
The base game map loads fine however so i don't think its DV.

I know you're looking into all these issues and i appreciate the time it takes to do so.

Many thanks.

**Comment by WhistleWiz** [comment]
I took a quick look at your log.
You can't run Mapify with Passenger Jobs right now. If you use the version before rural stations got added it will work.
Pax jobs will try to find certain tracks to create the rural stations, which will fail with custom maps, and thus freeze the game.

**Comment by Kelticcol** [comment]
Stupid question here, how do i change this, or can i disable pas jobs in mod menu?
Yet before it loaded fine... lol

**Comment by Kelticcol** [comment]
Once I disabled passenger jobs my custom maps load perfectly 👌 😁😁🥰.

Cheers for your assistance.

**Comment by t0stiman** [comment]
I've made a fix
https://github.com/katycat5e/DVPassengerJobs/pull/48

**Comment by Kelticcol** [comment]
How do i acquire said fix?

**Comment by t0stiman** [comment]
[PassengerJobs.zip](https://github.com/Insprill/dv-mapify/files/13708110/PassengerJobs.zip)

**Comment by Kelticcol** [comment]
Awesome, I shall download later today and let you know how it goes.

Also I know it's slightly off topic, but I may have found how to create
tunnels.

Work is in progress currently and will update you soon. [Hopefully it
works]

Cheers, keep well.

**Comment by Kelticcol** [comment]
Well this is annoying...... Loaded in the zip (overwrite the base passenger job file)
Loaded custom map with the PAS Job enabled got this.
Disabled PAS jobs still got this: 

![20231219113048_1](https://github.com/Insprill/dv-mapify/assets/152837201
/498a5971-ca5b-4ff0-aecb-a951b4fb5f6b)

**Comment by t0stiman** [comment]
Uhhhh, I have no idea what's going on there

**Comment by Kelticcol** [comment]
LOL , Well that makes 2 of us. i reloaded the map, minus the sleepers. Issue gone. no sleepers though.

**Comment by t0stiman** [comment]
The PR has been merged, you can close this issue @Insprill
