### ISSUE TITLE
Animated Scenery/Objects

### ISSUE THREAD

**Issue by Kelticcol** [Insprill/dv-mapify#56]
On my map i have a few objects that are animated, yet in game they don't work.

Should i put them in the streaming assets or game content?

Cheers. :)

**Comment by Insprill** [comment]
Anything that's not gameplay related (e.g. stations) should go in the streaming scene. Make sure the animator is setup correctly, and remember that custom scripts are not exported.

**Comment by Kelticcol** [comment]
Ahh OK cheers. any way to get the custom scripts exported over?

**Comment by WhistleWiz** [comment]
You'd need to either include them with Mapify itself or have them be a custom mod that gets loaded with the map.

**Comment by Kelticcol** [comment]
Ahh OK cheers.
