### ISSUE TITLE
Game freezes at 36%

### ISSUE THREAD

**Issue by SpikyTV** [Insprill/dv-mapify#77]
![image](https://github.com/user-attachments/assets/1930c418-33f0-4580-adc3-70b40cad12a0)
game freezes at 36% when loading test map

**Comment by t0stiman** [comment]
Does this bug still occur if you use this version of Mapify: https://github.com/t0stiman/dv-mapify/releases/tag/v2024.02.12 ?

If so please send your Player.log file here. 

> Open a File Explorer window.
> In the address bar (not the search bar), copy-paste the following and hit Enter:
> %APPDATA%\..\LocalLow\Altfuture\Derail Valley
> You should see a file named Player or Player.log.
