### ISSUE TITLE
Mapify.Editor.Cargo does not match DV.Logic.Job.CargoType anymore

### ISSUE THREAD

**Issue by t0stiman** [Insprill/dv-mapify#79]
Should be updated to match again or changed so we don't need to copy this enum from the base game.

**Comment by t0stiman** [comment]
@Insprill I'm assuming you copied the enum just to add Passengers to it?

**Comment by Insprill** [comment]
Been awhile since I wrote it but i believe it was primarily so you could select the vanilla cargo types in inspector windows, and they'd always be valid in-game. Passenger jobs was the only modded cargo at the time (excluding ccl) which is why it's there. The whole passenger jobs integration needs redone iirc.

**Comment by WhistleWiz** [comment]
Is there a version of the cargo that allows manually inputting string IDs (for custom cargo)?

It could be changed to be similar to something I made for CCL, where there's a string field for the ID that automatically draws a dropdown with preset options too ([usage](https://github.com/derail-valley-modding/custom-car-loader/blob/41edb4f96414acfa3af267168696c63f65b3000e/CCL.Types/CustomCarType.cs#L81)/[definition](https://github.com/derail-valley-modding/custom-car-loader/blob/master/CCL.Types/StringAndSelectorFieldAttribute.cs)/[implementation](https://github.com/derail-valley-modding/custom-car-loader/blob/master/CCL.Creator/Inspector/StringAndSelectorFieldAttributeEditor.cs)).

The implementation part has a few extras to support the CCL editor settings asset. A similar thing could be made to with assess to the MapInfo asset instead.

**Comment by t0stiman** [comment]
Related error I found in the log file:

```
Something broke while loading hazmat: Different number of cargo types: 89 in file vs 84 in game 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

InvalidOperationException: Different number of cargo types: 89 in file vs 84 in game
  at HazmatTileManager.DeserializeFromStream (System.IO.Stream input) [0x00066] in <70ee5fc687bb4c8989678a43730aadaa>:0 
  at HazmatTileManager.Deserialize (System.Byte[] rawBytes) [0x0004d] in <70ee5fc687bb4c8989678a43730aadaa>:0 
  at StartGameData_FromSaveGame+<LoadingNonBlockingCoro>d__10.MoveNext () [0x00cd2] in <70ee5fc687bb4c8989678a43730aadaa>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
<LoadingNonBlockingCoro>d__10:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: <70ee5fc687bb4c8989678a43730aadaa> Line: 0)
```

**Comment by WhistleWiz** [comment]
Yeah that's a bug with Custom Cargo that I won't fix. It causes no gameplay issues (if you add or remove cargo between sessions of the same save, it'll show up and will clear all hazmat tiles (spills, fires...) on load, but will work normally afterwards).

Fixing it would require changing a rather strict save structure for those tiles which is not worth at all.

**Comment by Insprill** [comment]
It's not a mod bug; it happens in vanilla, too, anytime new cargo is added. It's fine to ignore.

**Comment by WhistleWiz** [comment]
Yeah, I guess I never noticed in vanilla because cargo doesn't get added or removed as often lol

Looking at vanilla logs is also rarer, but yeah non-issue basically.
