### ISSUE TITLE
Attach mapify.unitypackage to release instead of in the repository

### ISSUE THREAD

**Issue by t0stiman** [Insprill/dv-mapify#86]
[mapify.unitypackage](https://github.com/Insprill/dv-mapify/blob/master/mapify.unitypackage) is a build artifact, so personally I think it should be an attachment to the release and not a committed file in the repository. This would also make it easier for users to find the right unitypackage for the Mapify version they use.

**Comment by WhistleWiz** [comment]
Is it not in the the releases too? I can see it here: https://github.com/Insprill/dv-mapify/releases/tag/v0.4.0

The latest one doesn't have a package attached however, I think it's because it didn't change anything from that release (just a few days apart)?
